### JWT 발급
POST http://localhost:8001/login
Content-Type: application/json

{
  "username": "fast",
  "password": "campus"
}

> {% client.global.set("authToken", response.body.token); %}

### JWT 발급 (ADMIN)
POST http://localhost:8001/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {% client.global.set("authToken", response.body.token); %}


### PAYMENT 서비스
GET http://localhost:8001/payments/1
Authorization: Bearer {{authToken}}

### BOOK 서비스 (with userId QueryParams)
GET http://localhost:8001/books/1?userId=admin
Authorization: Bearer {{authToken}}

###
GET http://localhost:8001/fastcampus/search/recommended