spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: payment-api
          uri: lb://payment-api # http://localhost:9002
          order: 1
          predicates:
            - Path=/payments/** # ?? ??? ?? ??? ??
          filters:
            - RewritePath=/payments/(?<segment>.*),/v1/payments/$\{segment}
        - id: book-api
          uri: lb://book-api # http://localhost:9001
          order: 1
          predicates:
            - Path=/books/**
          filters:
            - RewritePath=/books/(?<segment>.*),/v1/books/$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true

jwt:
  secret: 1ad35d74dc65cc0ee9a3a409f7f87e332aa6aa89d9cc64c66cdf9a1ffdc534ee