spring:
  application:
    name: payment-api

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true