spring:
  application:
    name: book-api

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true